services:
- type: web
  name: angelicastrong
  runtime: static
  buildCommand: npm run net-build
  staticPublishPath: ./client/dist
- type: web
  name: portfoliobackend
  runtime: node
  startCommand: npm start