services:
- type: web
  name: frontend
  env: static
  buildCommand: npm run net-build
  staticPublishPath: ./build
- type: web
  name: backend
  env: node
  buildCommand: npm run setup
  startCommand: npm start